image: python:latest

before_script:
  - export PATH="/root/.local/bin:$PATH"

job1:
  script:
    - echo "Hello, world!"


installing_dependencies:
  script:
    - apt-get update
    - apt-get install -y python3-pip
    - curl -sSL https://install.python-poetry.org/ | python3 - --git https://github.com/python-poetry/poetry.git@master
    - cd week3
    - poetry install


test_job:
  stage: test
  script: 
    - cd week3
    - python3 -m unitTests
