image: python:latest

stages:
  - build
  - test
  - deploy

before_script:
  - export PATH="/root/.local/bin:$PATH"

job1:
  stage: build
  script:
    - echo "Hello, world!"


installing_dependencies:
  stage: build
  script:
    - apt-get update
    - apt-get install -y python3-pip
    - curl -sSL https://install.python-poetry.org/ | python3 - --git https://github.com/python-poetry/poetry.git@master
    - cd week3
    - poetry install

build_and_release:
  stage: deploy
  script:
    - apt-get update
    - curl -sSL https://install.python-poetry.org/ | python3 - --git https://github.com/python-poetry/poetry.git@master
    - cd week3
    - poetry install
    - poetry run python3 main_cli.py
  only:
    refs:
      - main
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'main'
  artifacts:
    paths:
      - week3/chart.txt
    expire_in: 1 week
  needs: 
    - [installing_dependencies]


test_job:
  stage: test
  script: 
    - cd week3
    - python3 -m unitTests
  needs: 
    - [installing_dependencies]
