image: python:latest

before_script:
  - export PATH="/root/.local/bin:$PATH"

job1:
  script:
    - echo "Hello, world!"


installing_dependencies:
  script:
    - apt-get update
    - apt-get install -y python3-pip
    - curl -sSL https://install.python-poetry.org/ | python3 - --git https://github.com/python-poetry/poetry.git@master
    - cd week3
    - poetry install

build_and_release:
  script:
    - >
      if [ "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" != "main" ]; then
        echo "Not building release job because we are not on the main branch";
      else
        apt-get update
        apt-get install -y python3-pip
        curl -sSL https://install.python-poetry.org/ | python3 - --git https://github.com/python-poetry/poetry.git@master
        cd week3
        poetry install
        poetry run python3 main_cli.py
      fi
  only:
    - main
  artifacts:
    paths:
      - week3/chart.txt
    expire_in: 1 week


test_job:
  stage: test
  script: 
    - cd week3
    - python3 -m unitTests
